# Exclude a variety of commonly ignored directories.
src = ["src", "tests"]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 90
indent-width = 4
target-version = "py310"
preview = true

[lint]
select = [
	# main
	"E", # pycodestyle errors
	"F", # flake8 base
	"W", # pycodestyle warnings
	"C90", # mccabe
	"I", # isort
	"N", # naming
	"S", # bandit
	# somewhat additional
	"B", # bugbear
	"C4", # comprehensions
	"DTZ", # datetimez
	"T10", # debugger
	"EM", # error messages
	"G", # logging format
	"INP", # implicit namespace packages
	"PIE", # pie - many minor issues
	"T20", # prints
	"PT", # pytest style
	"RSE", # raises
	"INT", # gettext
	"RET", # returns
	"SLF", # private member access (_)
	"SIM", # simplify
	"SLOT", # slots
	"TID", # tidy imports
	"TCH", # typecheck-related
	"ARG", # arguments
	"PTH", # pathlib
	"ERA", # erradicate
	"LOG", # logging
	"PL", # pyling
	"TRY", # tryceratops
	"RUF", # ruff
	"UP", # pyupgrade
	"A", # builins
	"ASYNC", # async
	"PYI", # pyi
	"TD", # todos
	"FIX", # fixme
	"PERF", # performance
	"FURB", # refurb
]
ignore = [
	# "D",
	# "UP",
	# "S101",
	# "ANN",
	# "A",
	# below are formatting related that can conflict with black-style formatting
	"W191",
	"E111",
	"E114",
	"E117",
	"D206",
	"D300",
	"Q000",
	"Q001",
	"Q002",
	"Q003",
	"COM812",
	"COM819",
	"ISC001",
	"ISC002",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-format = true
docstring-code-line-length = "dynamic"
